-- CREATE PROCEDURE ATUALIZA_IMPOSTO @MES , 

-- SELECT das três tabelas que utilizaremos:
SELECT * FROM [NOTAS FISCAIS]
SELECT * FROM [ITENS NOTAS FISCAIS]
SELECT * FROM [TABELA DE PRODUTOS]

-- Select com JOIN das 3 tabelas:
SELECT A.DATA, A.IMPOSTO, B.[CODIGO DO PRODUTO], C.EMBALAGEM FROM 
[NOTAS FISCAIS] A INNER JOIN [ITENS NOTAS FISCAIS] B ON
A.NUMERO = B.NUMERO
INNER JOIN [TABELA DE PRODUTOS] C ON
B.[CODIGO DO PRODUTO] = C.[CODIGO DO PRODUTO]
WHERE MONTH(A.DATA) = 1 AND YEAR(A.DATA) = 2017
AND EMBALAGEM = 'PET'

-- UPDATE que utilizaremos na procedure
UPDATE [NOTAS FISCAIS] SET
IMPOSTO = '' FROM
[NOTAS FISCAIS] A INNER JOIN [ITENS NOTAS FISCAIS] B ON
A.NUMERO = B.NUMERO
INNER JOIN [TABELA DE PRODUTOS] C ON
B.[CODIGO DO PRODUTO] = C.[CODIGO DO PRODUTO]
WHERE MONTH(A.DATA) = 1 AND YEAR(A.DATA) = 2017
AND EMBALAGEM = 'PET'

-- Criando Procedure:
CREATE PROCEDURE ATUALIZA_IMPOSTO @MES AS INT, @ANO AS INT, @ALIQUOTA AS FLOAT, @TIPO_DE_PRODUTO AS VARCHAR(20)
AS
BEGIN
UPDATE [NOTAS FISCAIS] SET
IMPOSTO = @ALIQUOTA 
FROM [NOTAS FISCAIS] A INNER JOIN [ITENS NOTAS FISCAIS] B ON
A.NUMERO = B.NUMERO
INNER JOIN [TABELA DE PRODUTOS] C ON
B.[CODIGO DO PRODUTO] = C.[CODIGO DO PRODUTO]
WHERE MONTH(A.DATA) = @MES AND YEAR(A.DATA) = @ANO
AND EMBALAGEM = @TIPO_DE_PRODUTO
END

-- Executando Procedure
EXEC ATUALIZA_IMPOSTO 
@MES = 1,
@ANO = 2017, 
@ALIQUOTA = 0,
@TIPO_DE_PRODUTO = 'PET'
ROLLBACK