-- SELECT que traz o faturamento de todos os clientes:
SELECT A.CPF, A.NOME, SUM(C.QUANTIDADE * C.PREÇO) AS FATURAMENTO 
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B ON 
A.CPF = B.CPF AND YEAR(B.DATA) = 2016 INNER JOIN
[ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO GROUP BY A.CPF, A.NOME

-- Criando um tipo:
CREATE TYPE LISTA_CLIENTES AS TABLE
(CPF VARCHAR(12) NOT NULL)

-- Criando uma variável, onde iremos inserir os CPFs dos clientes:
DECLARE @LISTA AS LISTA_CLIENTES
INSERT INTO @LISTA (CPF) VALUES ('19290992743'), ('5576228758'), ('95939180787')

-- Select inicial, mas agora juntando a tabela temporária LISTA, que criamos na linha anterior:
SELECT A.CPF, A.NOME, SUM(C.QUANTIDADE * C.PREÇO) AS FATURAMENTO 
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B ON 
A.CPF = B.CPF AND YEAR(B.DATA) = 2016 INNER JOIN
[ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO INNER JOIN @LISTA D ON A.CPF = D.CPF
GROUP BY A.CPF, A.NOME

-- Criando a procedure, que receberá uma tabela como parâmetro:
CREATE PROCEDURE FATURAMENTO_CLIENTES_2016 @LISTA AS LISTA_CLIENTES READONLY AS

SELECT A.CPF, A.NOME, SUM(C.QUANTIDADE * C.PREÇO) AS FATURAMENTO 
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B ON 
A.CPF = B.CPF AND YEAR(B.DATA) = 2016 INNER JOIN
[ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO INNER JOIN @LISTA D ON A.CPF = D.CPF
GROUP BY A.CPF, A.NOME

-- Executando Procedure:
DECLARE @LISTA AS LISTA_CLIENTES
INSERT INTO @LISTA (CPF) VALUES ('19290992743'), ('5576228758'), ('95939180787')
EXEC FATURAMENTO_CLIENTES_2016 @LISTA = @LISTA