-- Criando o tipo de lista de datas
CREATE TYPE LISTA_DATAS AS TABLE (DATA DATE)

-- Criando a variável LISTA a qual atribuiremos as datas das vendas:
DECLARE @LISTA LISTA_DATAS 
INSERT INTO @LISTA (DATA) VALUES ('2015-01-01'),('2016-03-26'),('2016-09-13')

CREATE PROCEDURE LISTA_NUMERO_NOTAS @LISTA AS LISTA_DATAS READONLY AS 
SELECT DATA, COUNT(*) AS NUMERO FROM [NOTAS FISCAIS]
WHERE DATA IN (SELECT DATA FROM @Lista)
GROUP BY DATA

-- Executando Procedure:
DECLARE @LISTA LISTA_DATAS 
INSERT INTO @LISTA (DATA) VALUES ('2015-01-01'),('2016-03-26'),('2016-09-13')
SELECT * FROM [NOTAS FISCAIS] 