-- Declarando variáveis:
DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(25), @PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT, @BAIRRO VARCHAR(100)

-- Atribuindo valores:
SET @MATRICULA = '00239'
SET @NOME = 'José Antônio'
SET @PERCENTUAL = 0.10
SET @FERIAS = 1
SET @DATA = '2017-09-17'
SET @BAIRRO = 'Meier'

-- Consultando tabela de vendedores:
SELECT * FROM [TABELA DE VENDEDORES]

-- Utilizando variáveis para realizar o insert
INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO) VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO)

-- Consulta da tabela de vendedores, com o novo registro:
SELECT * FROM [TABELA DE VENDEDORES]