-- Select que calcula o faturamento de uma nota 
SELECT SUM (QUANTIDADE * PREÇO) FROM [ITENS NOTAS FISCAIS] WHERE NUMERO = 100

CREATE FUNCTION FATURAMENTO_NOTA (@NUMERO AS INT) RETURNS FLOAT
AS
BEGIN
	DECLARE @FATURAMENTO FLOAT
	SELECT @FATURAMENTO = SUM (QUANTIDADE * PREÇO) FROM [ITENS NOTAS FISCAIS] WHERE NUMERO = @NUMERO
	RETURN @FATURAMENTO
END

-- Utilizando a função criada anteriomente
SELECT NUMERO, [dbo].[FATURAMENTO_NOTA](NUMERO) AS FATURAMENTO FROM [NOTAS FISCAIS]