-- Deletando função, caso ela já exista
IF OBJECT_ID ('ENDERECO_COMPLETO2','FN') IS NOT NULL
	DROP FUNCTION [dbo].[ENDERECO_COMPLETO2]

-- Criando uma função de exemplo:
CREATE FUNCTION ENDERECO_COMPLETO2 (@ENDERECO VARCHAR(100), @CIDADE VARCHAR(50), @ESTADO VARCHAR(50), @CEP VARCHAR(20)) RETURNS VARCHAR (250) AS
BEGIN 
	DECLARE @ENDERECO_COMPLETO VARCHAR (250) = @ENDERECO + ' - ' + @CIDADE + ' - ' + @ESTADO + ' - ' + @CEP
	RETURN @ENDERECO_COMPLETO
END